### ISSUE TITLE
newfstatat(2) support - loki

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#350]
https://github.com/grafana/loki

```
level=info ts=2019-01-09T00:18:43.36744Z caller=loki.go:121 msg=initialising module=store
 1 write
level=info ts=2019-01-09T00:18:43.371819Z caller=override.go:33 msg="per-tenant overides disabled"
 1 newfstatat
nosyscall newfstatat
 1 write
level=error ts=2019-01-09T00:18:43.37465Z caller=main.go:41 msg="error initialising loki" err="error initialising module: store: error creating index client: stat /tmp/loki/index: function not implemented"
 1 exit_group
exit_groupexit status 1
```

```
eyberg@dungeon:~/loki$ ops run -p 3100 -c config.json -d -f loki^C
eyberg@dungeon:~/loki$ cat config.json
{
    "Args":["loki", "-config.file", "/loki.yml"],
    "Files":["loki.yml"]
}
eyberg@dungeon:~/loki$ cat loki.yml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      store: inmemory
      replication_factor: 1

schema_config:
  configs:
  - from: 0
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunkseyberg@dungeon:~/loki$
```

this is trying to create an index in /tmp using boltdb - which I believe the current lib for that is -> https://github.com/etcd-io/bbolt
