### ISSUE TITLE
h2o tracking tkt

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#835]
this was taken from h2o the webserver but I've seen these tmp folders not get created with other apps too - i work around it for now just by creating the tmp dir 

```
eyberg@s1:~/h2/h2o-2.3.0-beta1$ cat config.json
{
  "Args": ["h2o", "-c", "examples/h2o/h2o.conf"],
  "Dirs": ["examples"]
}
```

```
filesystem_mkentry error: a path component ("tmp") is missing
failed to create temporary directory under /tmp:No such file or directory
```

```
1 mkdir
1 mkdir: "/tmp/openssl-privsep.baXtsG", mode 0x1c0
filesystem_mkentry error: a path component ("tmp") is missing
```

not sure if it's related to this or not -> https://github.com/nanovms/nanos/issues/834

**Comment by eyberg** [comment]
looks like this might be dying on ipv6 which then subsequently dies on an invalid signal being sent upon shutdown

```
1 write
socket(2) failed:Address family not supported by protocol
1 direct return: 58, rsp 0x76c58008
1 run thread, cpu 0, frame 0x0000000100e05800, rip 0x8f6110154, rsp 0x76c58008, rdi 0x2, rax 0x3a, rflags 0x246, cs 0x2b, sysret
1 rt_sigprocmask
1 direct return: 0, rsp 0x76c5a738
1 run thread, cpu 0, frame 0x0000000100e05800, rip 0x8f603f14d, rsp 0x76c5a738, rdi 0x1, rax 0x0, rflags 0x202, cs 0x2b, sysret
1 rt_sigprocmask
1 direct return: 0, rsp 0x76c5a620
1 run thread, cpu 0, frame 0x0000000100e05800, rip 0x8f603ee56, rsp 0x76c5a620, rdi 0x0, rax 0x0, rflags 0x246, cs 0x2b, sysret
1 getpid
1 direct return: 2, rsp 0x76c5a620
1 run thread, cpu 0, frame 0x0000000100e05800, rip 0x8f603ee5f, rsp 0x76c5a620, rdi 0x0, rax 0x2, rflags 0x246, cs 0x2b, sysret
1 gettid
1 direct return: 1, rsp 0x76c5a620
1 run thread, cpu 0, frame 0x0000000100e05800, rip 0x8f603ee69, rsp 0x76c5a620, rdi 0x2, rax 0x1, rflags 0x246, cs 0x2b, sysret
1 tgkill
1 direct return: 0, rsp 0x76c5a620
1 run thread, cpu 0, frame 0x0000000100e05800, rip 0x8f603ee75, rsp 0x76c5a620, rdi 0x2, rax 0x0, rflags 0x246, cs 0x2b, sysret
1 rt_sigprocmask
1 direct return: 0, rsp 0x76c5a620
dispatch_signals error: signal 6 resulting in core dump
unimplemented signal
exit status 255
```

```
{
  "Dirs": ["tmp"],
  "Files": ["h2o.conf", "server.crt", "server.key"],
  "Args": ["h2o", "-c", "h2o.conf"]
}
```

ran into https://github.com/h2o/h2o/issues/1285 - seems like ipv6 is still present even when it is not used

**Comment by eyberg** [comment]
this might need a patch or some other config setting to be toggled ->

```
1 clone
1 clone: flags 1200011, child_stack 0x0000000000000000, ptid 0x0000000000000000, ctid 0x0000000142978b50, newtls 0
1 attempted to fork by passing null child stack, aborting.
```

**Comment by francescolavra** [comment]
Tested h2o-2.3.0-beta2, and after a few changes to the default configuration, it works.
```
francesco@ubuntu:~/.ops/instances/h2o$ cat config.json 
{
  "Dirs": ["etc", "tmp"],
  "Files": ["h2o.conf", "server.crt", "server.key", "alternate.crt", "alternate.key", "/etc/nsswitch.conf", "/lib/x86_64-linux-gnu/libnss_compat.so.2", "/lib/x86_64-linux-gnu/libnsl.so.1", "/lib/x86_64-linux-gnu/libnss_nis.so.2", "/lib/x86_64-linux-gnu/libnss_files.so.2"],
  "MapDirs": {"/usr/src/h2o-2.3.0-beta2/share/*": "usr/local/share/"},
  "MapDirs": {"/usr/src/h2o-2.3.0-beta2/examples/doc_root/*": "doc_root/"},
  "MapDirs": {"/usr/src/h2o-2.3.0-beta2/examples/doc_root.alternate/*": "doc_root.alternate/"},
  "RunConfig": {
    "Ports": [8080, 8081]
  },
  "Args": ["h2o", "-c", "h2o.conf"]
}
```
```
francesco@ubuntu:~/.ops/instances/h2o$ tree
.
├── alternate.crt -> /usr/src/h2o-2.3.0-beta2/examples/h2o/alternate.crt
├── alternate.key -> /usr/src/h2o-2.3.0-beta2/examples/h2o/alternate.key
├── config.json
├── etc
│   └── passwd
├── h2o -> /usr/src/h2o-2.3.0-beta2/h2o
├── h2o.conf
├── server.crt -> /usr/src/h2o-2.3.0-beta2/examples/h2o/server.crt
├── server.key -> /usr/src/h2o-2.3.0-beta2/examples/h2o/server.key
└── tmp
```
```
francesco@ubuntu:~/.ops/instances/h2o$ cat etc/passwd 
root:x:0:0:root:/root:/bin/nobash
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
```
(compared to the default /etc/passwd file created by Ops, we need the "nobody" user entry too)
```
francesco@ubuntu:~/.ops/instances/h2o$ cat h2o.conf 
# to find out the configuration commands, run: h2o --help

listen: 8080
listen:
  port: 8081
  ssl:
    certificate-file: server.crt
    key-file: server.key
    minimum-version: TLSv1.2
    neverbleed: off
    ocsp-update-interval: 0
    cipher-preference: server
    cipher-suite: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
    # Oldest compatible clients: Firefox 27, Chrome 30, IE 11 on Windows 7, Edge, Opera 17, Safari 9, Android 5.0, and Java 8
    # see: https://wiki.mozilla.org/Security/Server_Side_TLS
hosts:
  "127.0.0.1.xip.io:8080":
    paths:
      /:
        file.dir: doc_root
    access-log: /dev/stdout
  "alternate.127.0.0.1.xip.io:8081":
    listen:
      port: 8081
      ssl:
        certificate-file: alternate.crt
        key-file: alternate.key
        neverbleed: off
        ocsp-update-interval: 0
    paths:
      /:
        file.dir: doc_root.alternate
    access-log: /dev/stdout
```
Starting from the default h2o configuration file, I had to disable Neverbleed (an OpenSSL engine that runs RSA private key operations in an isolated process) and the OCSP updater (which tries to run the share/h2o/fetch-ocsp-response shell script).
```
francesco@ubuntu:~/.ops/instances/h2o$ ops run -c config.json h2o
warning: overwriting existing file /etc/passwd hostpath old: /tmp/h2o_temp074839026/passwd new: etc/passwd
[h2o -c h2o.conf]
booting /home/francesco/.ops/images/h2o.img ...
assigned: 10.0.2.15
[INFO] raised RLIMIT_NOFILE to 65536
h2o server (pid:1) is ready to serve requests with 1 threads
```
The server is then accessible at http://127.0.0.1:8080/ and https://127.0.0.1:8081/
